" _____
"| ____|__ _  __| | ___   _____   _(_)_ __ ___  _ __ ___
"|  _| / _` |/ _` |/ _ \ / __\ \ / / | '_ ` _ \| '__/ __|
"| |__| (_| | (_| | (_) | (__ \ V /| | | | | | | | | (__
"|_____\__, |\__,_|\___/ \___| \_/ |_|_| |_| |_|_|  \___|
"       |___/



execute pathogen#infect()
execute pathogen#helptags()

                             "< Plugins settings >


" Airline
let g:airline_powerline_fonts = 1

" Gitgutter
let gitgutter_max_signs = 500

" NERDTree
let NERDTreeMinimalUI = 0
let NERDTreeDirArrows = 1
let NERDTreeAutoDeleteBuffer = 1
let NERDTreeShowHidden=1
autocmd BufWinEnter * silent! NERDTreeMirror


                             "< Editor settings >
set nocompatible
syntax on
filetype indent on
filetype plugin on
set autoindent
set autoread
set background=dark
set clipboard=unnamedplus
set colorcolumn=80,120
set expandtab
set fileformat=unix
set foldlevel=99
set foldmethod=indent
set hlsearch
set ignorecase
set incsearch
set list
set listchars=trail:·,tab:▸\ ,eol:¬
set modifiable
set mouse=a
set noswapfile
set number
set pastetoggle=<F2>
set path+=**
set ruler
set shiftround
set shiftwidth=2
set showmatch
set signcolumn=yes
set smartcase
set softtabstop=2
set splitbelow
set splitright
set t_8b=[48;2;%lu;%lu;%lum
set t_8f=[38;2;%lu;%lu;%lum
set t_Cs=
set textwidth=79
set title
set wildmenu
set wildmode=longest:full,full

if $TERM=~'linux'
  "Running in TTY
  set colorcolumn=
  colorscheme elflord
  let g:airline_disable_statusline = 1
else
  "Terminal emulator
  if &t_Co == 256 && has('termguicolors')
    set termguicolors
    let ayucolor="light"
    colorscheme ayu
  else
    colorscheme elflord
  endif
endif

" Autocommands
augroup autorun
  autocmd BufEnter * silent! lcd %:p:h
  autocmd BufWritePre * %s/\s\+$//e
augroup end


                                 "< Mappings >

let g:mapleader = ','

" Sorting in visual mode
vnoremap <Leader>s :sort<CR>

" Automatically format text with set max width
nnoremap <F6> :set textwidth=72<CR>gqj:set textwidth=79<CR>
nnoremap <S-F6> :set textwidth=79<CR>gqj:set textwidth=79<CR>

nnoremap <F7> :set cursorcolumn!<CR>
nnoremap <F9> :NERDTreeToggle<CR>
nnoremap <F12> :set spell! spelllang=en_us<CR>

" Use space to fold a block of code
nnoremap <space> za

" Unhighlighd text
nnoremap <C-A> :noh<CR>

" Maintain selection (re-select) when shifting left or right in visual mode
vnoremap < <gv
vnoremap > >gv

" Easier navigation in splits
nnoremap <C-H> <C-W>h
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l

" Use the force, Luke.
nnoremap <up> <nop>
inoremap <up> <nop>
vnoremap <up> <nop>
nnoremap <down> <nop>
inoremap <down> <nop>
vnoremap <down> <nop>
nnoremap <left> <nop>
inoremap <left> <nop>
vnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <right> <nop>
vnoremap <right> <nop>

command! Mktags !ctags -R .

if &rtp =~ 'coc.nvim'
  let g:coc_global_extensions = [
    \'coc-css',
    \'coc-python',
    \'coc-html',
    \'coc-json',
    \'coc-tsserver',
    \'coc-yaml'
  \]

  set signcolumn=yes

  " TextEdit might fail if hidden is not set.
  set hidden

  " Some servers have issues with backup files, see #649.
  set nobackup
  set nowritebackup

  " Give more space for displaying messages.
  set cmdheight=2

  " Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
  " delays and poor user experience.
  set updatetime=300

  " Don't pass messages to |ins-completion-menu|.
  set shortmess+=c

  " Use tab for trigger completion with characters ahead and navigate.
  " NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
  " other plugin before putting this into your config.
  inoremap <silent><expr> <TAB>
    \ pumvisible() ? "\<C-n>" :
    \ <SID>check_back_space() ? "\<TAB>" :
    \ coc#refresh()
  inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

  function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
  endfunction

  " Use <c-space> to trigger completion.
  inoremap <silent><expr> <c-space> coc#refresh()

  " Use <cr> to confirm completion, `<C-g>u` means break undo chain at current
  " position. Coc only does snippet and additional edit on confirm.
  " <cr> could be remapped by other vim plugin, try `:verbose imap <CR>`.
  if exists('*complete_info')
    inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
  else
    inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
  endif

  " Use `[g` and `]g` to navigate diagnostics
  nmap <silent> [g <Plug>(coc-diagnostic-prev)
  nmap <silent> ]g <Plug>(coc-diagnostic-next)

  " GoTo code navigation.
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)

  " Use K to show documentation in preview window.
  nnoremap <silent> K :call <SID>show_documentation()<CR>

  function! s:show_documentation()
    if (index(['vim','help'], &filetype) >= 0)
      execute 'h '.expand('<cword>')
    else
      call CocAction('doHover')
    endif
  endfunction

  " Highlight the symbol and its references when holding the cursor.
  autocmd CursorHold * silent call CocActionAsync('highlight')

  " Symbol renaming.
  nmap <leader>rn <Plug>(coc-rename)

  " Formatting selected code.
  xmap <leader>f  <Plug>(coc-format-selected)
  nmap <leader>f  <Plug>(coc-format-selected)

  augroup mygroup
    autocmd!
    " Setup formatexpr specified filetype(s).
    autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
    " Update signature help on jump placeholder.
    autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
  augroup end

  " Applying codeAction to the selected region.
  " Example: `<leader>aap` for current paragraph
  xmap <leader>a  <Plug>(coc-codeaction-selected)
  nmap <leader>a  <Plug>(coc-codeaction-selected)

  " Remap keys for applying codeAction to the current buffer.
  nmap <leader>ac  <Plug>(coc-codeaction)
  " Apply AutoFix to problem on the current line.
  nmap <leader>qf  <Plug>(coc-fix-current)

  " Map function and class text objects
  " NOTE: Requires 'textDocument.documentSymbol' support from the language server.
  xmap if <Plug>(coc-funcobj-i)
  omap if <Plug>(coc-funcobj-i)
  xmap af <Plug>(coc-funcobj-a)
  omap af <Plug>(coc-funcobj-a)
  xmap ic <Plug>(coc-classobj-i)
  omap ic <Plug>(coc-classobj-i)
  xmap ac <Plug>(coc-classobj-a)
  omap ac <Plug>(coc-classobj-a)

  " Use CTRL-S for selections ranges.
  " Requires 'textDocument/selectionRange' support of LS, ex: coc-tsserver
  nmap <silent> <C-s> <Plug>(coc-range-select)
  xmap <silent> <C-s> <Plug>(coc-range-select)

  " Add `:Format` command to format current buffer.
  command! -nargs=0 Format :call CocAction('format')

  " Add `:Fold` command to fold current buffer.
  command! -nargs=? Fold :call     CocAction('fold', <f-args>)

  " Add `:OR` command for organize imports of the current buffer.
  command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

  " Add (Neo)Vim's native statusline support.
  " NOTE: Please see `:h coc-status` for integrations with external plugins that
  " provide custom statusline: lightline.vim, vim-airline.
  set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

  " Mappings using CoCList:
  " Show all diagnostics.
  nnoremap <silent> <space>a  :<C-u>CocList diagnostics<cr>
  " Manage extensions.
  nnoremap <silent> <space>e  :<C-u>CocList extensions<cr>
  " Show commands.
  nnoremap <silent> <space>c  :<C-u>CocList commands<cr>
  " Find symbol of current document.
  nnoremap <silent> <space>o  :<C-u>CocList outline<cr>
  " Search workspace symbols.
  nnoremap <silent> <space>s  :<C-u>CocList -I symbols<cr>
  " Do default action for next item.
  nnoremap <silent> <space>j  :<C-u>CocNext<CR>
  " Do default action for previous item.
  nnoremap <silent> <space>k  :<C-u>CocPrev<CR>
  " Resume latest coc list.
  nnoremap <silent> <space>p  :<C-u>CocListResume<CR>
endif
