" _____
"| ____|__ _  __| | ___   _____   _(_)_ __ ___  _ __ ___
"|  _| / _` |/ _` |/ _ \ / __\ \ / / | '_ ` _ \| '__/ __|
"| |__| (_| | (_| | (_) | (__ \ V /| | | | | | | | | (__
"|_____\__, |\__,_|\___/ \___| \_/ |_|_| |_| |_|_|  \___|
"       |___/


execute pathogen#infect()
execute pathogen#helptags()

                             "< Plugins settings >

" Gitgutter
let gitgutter_max_signs = 500

" NERDTree
let NERDTreeAutoDeleteBuffer = 1
let NERDTreeShowHidden=1
au BufWinEnter * silent! NERDTreeMirror

" Ayu colorscheme
let ayucolor="mirage"

                             "< Editor settings >

filetype plugin on
filetype indent on
syntax on
set autoindent
set autoread
set background=dark
set clipboard=unnamedplus
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set fileformat=unix
set hlsearch
set ignorecase
set smartcase
set incsearch
set list
set listchars=trail:·,tab:▸\ ,eol:$
set modifiable
set mouse=a
set noswapfile
set number
set pastetoggle=<F2>
set path+=**
set ruler
set textwidth=79
set shiftround
set showmatch
set signcolumn=yes
set splitbelow
set splitright
set title
set wildmenu
set wildmode=longest:full,full

if $TERM=~'linux'
  "Running in TTY
  colorscheme elflord
else
  "Terminal emulator
  if &t_Co == 256 && has('termguicolors')
    set termguicolors
    colorscheme ayu
  else
    colorscheme elflord
  endif
endif

" Autocommands
augroup autorun
  autocmd BufEnter * silent! lcd %:p:h
  autocmd BufWritePre * %s/\s\+$//e
augroup end

let g:mapleader = ','

nnoremap <F7> :set cursorcolumn!<CR>
nnoremap <F9> :NERDTreeToggle<CR>
nnoremap <F12> :set spell! spelllang=en_us<CR>

" Re-select when shifting left or right in visual mode
vnoremap < <gv
vnoremap > >gv

" Easier navigation in splits
nnoremap <C-H> <C-W>h
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l

" Use the force, Luke.
nnoremap <up> <nop>
inoremap <up> <nop>
vnoremap <up> <nop>
nnoremap <down> <nop>
inoremap <down> <nop>
vnoremap <down> <nop>
nnoremap <left> <nop>
inoremap <left> <nop>
vnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <right> <nop>
vnoremap <right> <nop>

command! Mktags !ctags -R .
