" _____
"| ____|__ _  __| | ___   _____   _(_)_ __ ___  _ __ ___
"|  _| / _` |/ _` |/ _ \ / __\ \ / / | '_ ` _ \| '__/ __|
"| |__| (_| | (_| | (_) | (__ \ V /| | | | | | | | | (__
"|_____\__, |\__,_|\___/ \___| \_/ |_|_| |_| |_|_|  \___|
"       |___/


" Automatically install Vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'ekalinin/Dockerfile.vim'
Plug 'evidens/vim-twig'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'altercation/vim-colors-solarized'
Plug 'ayu-theme/ayu-vim'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()


                             "< Plugins settings >

" Gitgutter
let gitgutter_max_signs = 500

" NERDTree
let NERDTreeAutoDeleteBuffer = 1
let NERDTreeShowHidden=1
autocmd BufWinEnter * silent! NERDTreeMirror

" Ayu colorscheme
let ayucolor="mirage"

                             "< Editor settings >

filetype plugin on
filetype indent on
syntax on
set autoindent
set autoread
set background=dark
set clipboard=unnamedplus
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set fileformat=unix
set hlsearch
set ignorecase
set smartcase
set incsearch
set list
set listchars=trail:·,tab:▸\ ,eol:$
set modifiable
set mouse=a
set noswapfile
set number
set pastetoggle=<F2>
set path+=**
set ruler
set textwidth=79
set shiftround
set showmatch
set signcolumn=no
set splitbelow
set splitright
set title
set wildmenu
set wildmode=longest:full,full

if $TERM=~'linux'
  "Running in TTY
  colorscheme elflord
else
  "Terminal emulator
  if &t_Co == 256 && has('termguicolors')
    set termguicolors
    colorscheme ayu
  else
    colorscheme elflord
  endif
endif

" Autocommands
augroup autorun
  autocmd BufEnter * silent! lcd %:p:h
  autocmd BufWritePre * %s/\s\+$//e
augroup end

let g:mapleader = ','

nnoremap <F7> :set cursorcolumn!<CR>
nnoremap <F9> :NERDTreeToggle<CR>
nnoremap <F12> :set spell! spelllang=en_us<CR>

" Re-select when shifting left or right in visual mode
vnoremap < <gv
vnoremap > >gv

" Easier navigation in splits
nnoremap <C-H> <C-W>h
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l

" Use the force, Luke.
nnoremap <up> <nop>
inoremap <up> <nop>
vnoremap <up> <nop>
nnoremap <down> <nop>
inoremap <down> <nop>
vnoremap <down> <nop>
nnoremap <left> <nop>
inoremap <left> <nop>
vnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <right> <nop>
vnoremap <right> <nop>

command! Mktags !ctags -R .

set hidden
"set cmdheight=2
set updatetime=300
set signcolumn=yes

" Use <c-space> to trigger completion
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" Use tab for trigger completion with characters ahead and navigate
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
inoremap <silent><expr> <TAB>
  \ pumvisible() ? "\<C-n>" :
  \ <SID>check_back_space() ? "\<TAB>" :
  \ coc#refresh()

" GoTo code navigation
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Remap <C-f> and <C-b> for scroll float windows/popups
if has('nvim-0.4.0') || has('patch-8.2.0750')
  nnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
  nnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
  inoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" :
  inoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" :
  vnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
  vnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
endif

" Status line support
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}
