#!/bin/bash
#
# ~/.xinitrc | ~/.xsession
#

# source configuration files in /etc/X11/xinit/xinitrc.d
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for script in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "${script}" ] && source "${script}"
  done
fi

# Start ssh agent
eval "$(ssh-agent)"

# Load .Xresources
[ -e "$HOME/.Xresources" ] && xrdb -load "$HOME/.Xresources" &

if [[ "$(cat /sys/class/drm/card0/*HDMI*/status)" == "connected" ]]; then
  xrandr --output HDMI-1 --primary --auto --output LVDS-1 --off &
fi

# Set root window color
type -p nitrogen && nitrogen --restore || xsetroot -solid "#2e3440" &

# Touchpad settings
touchpad_id=$(xinput | grep -i touchpad | cut -f2 | tr -d "id=")
xinput --set-prop "${touchpad_id}" "libinput Tapping Enabled" 1 &
xinput --set-prop "${touchpad_id}" "libinput Disable While Typing Enabled" 1 &

# Applets
nm-applet &
system-config-printer-applet &

# Keyboard settings
numlockx &
setxkbmap -option terminate:ctrl_alt_bksp &

# Lock screen when going to sleep
xss-lock -- i3lock -c 2e3440  &

# launch the window manager
exec "${1:-i3}"
