# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# Aliases
alias venv='virtualenv venv &> /dev/null && source venv/bin/activate'
alias wifiscan='nmcli device wifi list'
alias dcompose-down="sudo docker-compose down --rmi all -v --remove-orphans"
alias starti3="startx ~/.xinitrc i3"

umask 022
