alias docker-compose-down="sudo docker-compose down --rmi all -v --remove-orphans"
alias urlencode='python -c "import sys, urllib.parse; print(urllib.parse.quote_plus(sys.argv[1]))"'
alias urldecode='python -c "import sys, urllib.parse; print(urllib.parse.unquote_plus(sys.argv[1]))"'
