# Get the aliases and functions
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

# Environment variables
export EDITOR="/usr/bin/vim"
export VISUAL="/usr/bin/vim"
export TERMINAL="/usr/bin/sakura"

# Add local folders to PATH
PATH=${PATH}:"${HOME}/.local/bin"
